import Head from 'next/head';
import Button from '@/components/button';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Hello React with Next.JS</h1>
        <br></br>

        <Button></Button>
      </main>
    </>
  )
}
